### ISSUE TITLE
NoSuchMethodError after Migrating from 1.6.2 to 1.6.3

### ISSUE THREAD

**Issue by andi-huber** [structurizr/java#181]
```
java.lang.NoSuchMethodError: 'java.lang.String com.structurizr.view.Terminology.findTerminology(com.structurizr.model.ModelItem)'
	at com.structurizr.io.plantuml.PlantUMLWriter.typeOf(PlantUMLWriter.java:356)
```

I got the above using the packages from Maven Central.

**Comment by simonbrowndotje** [comment]
v1.6.3 is a two year old release, and no longer supported, so there's not much I can suggest here aside from upgrading further. Sorry!

**Comment by andi-huber** [comment]
My bad, the `1,6,2 -> 1.6.3` upgrade vector originated from _GitHub's_ `dependabot`. I did not realize there are newer versions. Thanks for the pointer!

**Comment by andi-huber** [comment]
For reference: We were combining` structurizr-core` with `structurizr-plantuml` using the same version number `1.6.3`. Of course that would not work.

Never mind and sorry for the noise!

**Comment by simonbrowndotje** [comment]
No problem. Just as an FYI though ... [structurizr-plantuml](https://github.com/structurizr/java-extensions/tree/master/structurizr-plantuml) is also no longer supported, and has been replaced by [structurizr-export](https://github.com/structurizr/export) that provides a unified API for exporting to multiple "diagrams as code" formats.
